"""User session update

Revision ID: 4625e1755491
Revises: f4c3b2a1d0e9
Create Date: 2026-06-24 10:17:04.036798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4625e1755491'
down_revision: Union[str, None] = 'f4c3b2a1d0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_enrollment_user_course', 'course_enrollments', ['user_id', 'course_id'])
    op.add_column('user_sessions', sa.Column('device_info', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'device_info')
    op.drop_constraint('uq_enrollment_user_course', 'course_enrollments', type_='unique')
    # ### end Alembic commands ###
