"""add_thumbnail_url_column

Revision ID: 6aba67161f70
Revises: a0b0ec4b6d80
Create Date: 2026-06-21 06:24:23.195070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aba67161f70'
down_revision: Union[str, None] = 'a0b0ec4b6d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'thumbnail_url')
    # ### end Alembic commands ###
