"""UUID Fix

Revision ID: 7fdcfc30d34b
Revises: 1d1b9436b94a
Create Date: 2026-06-18 04:34:16.064601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdcfc30d34b'
down_revision: Union[str, None] = '1d1b9436b94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
