"""Update tables

Revision ID: a0b0ec4b6d80
Revises: 80706d0333ae
Create Date: 2026-06-20 05:38:22.652269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b0ec4b6d80'
down_revision: Union[str, None] = '80706d0333ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'badge')
    op.drop_column('courses', 'discount_price')
    op.create_unique_constraint('uq_user_lesson_progress', 'lesson_progress', ['user_id', 'lesson_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_lesson_progress', 'lesson_progress', type_='unique')
    op.add_column('courses', sa.Column('discount_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('badge', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
