"""Update Review

Revision ID: e6c5227d0aa5
Revises: 4625e1755491
Create Date: 2026-06-25 15:22:08.902870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c5227d0aa5'
down_revision: Union[str, None] = '4625e1755491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_reports_review_id'), 'review_reports', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_reports_user_id'), 'review_reports', ['user_id'], unique=False)
    op.add_column('reviews', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reviews', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=False)
    op.create_index(op.f('ix_reviews_is_deleted'), 'reviews', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_is_deleted'), table_name='reviews')
    op.alter_column('reviews', 'rating',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('reviews', 'is_deleted')
    op.drop_column('reviews', 'deleted_at')
    op.drop_index(op.f('ix_review_reports_user_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_review_id'), table_name='review_reports')
    op.drop_table('review_reports')
    # ### end Alembic commands ###
